/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include	<stdint.h>
#include	"stm32f4xx.h"
#include	"stm32f4xx_ll_bus.h"
#include	"stm32f4xx_ll_tim.h"
#include	"stm32f4xx_ll_gpio.h"
#include	"stm32f4xx_ll_exti.h"
#include	"stm32f4xx_ll_adc.h"
#include 	"stm32f4xx_ll_usart.h"
#include 	<stdio.h>

#define Clock 	GPIOB, LL_GPIO_PIN_2
#define	Data	GPIOB, LL_GPIO_PIN_1
#define CE		GPIOB, LL_GPIO_PIN_15


uint8_t Temp_DHT11[5] = {0};

void TIM1_IRQHandler()
{
	if(LL_TIM_IsActiveFlag_UPDATE(TIM1))
	{

		LL_TIM_ClearFlag_UPDATE(TIM1);
	}

}

void USART2_IRQHandler()
{
	if (LL_USART_IsActiveFlag_RXNE(USART2))
	{
		uint8_t receivedData = LL_USART_ReceiveData8(USART2);
		if(receivedData=='1')
		{
			LL_GPIO_TogglePin(GPIOA, LL_GPIO_PIN_5);
		}
		LL_USART_TransmitData8(USART2, receivedData);
	}


}


void Delay(uint16_t AutoReload)
{
	LL_TIM_SetAutoReload(TIM2, AutoReload);
	LL_TIM_ClearFlag_UPDATE(TIM2);
	LL_TIM_EnableCounter(TIM2);
	while (!LL_TIM_IsActiveFlag_UPDATE(TIM2));
	LL_TIM_DisableCounter(TIM2);
	LL_TIM_ClearFlag_UPDATE(TIM2);
}

void DHT11()
{
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_0, LL_GPIO_MODE_OUTPUT);
	LL_GPIO_ResetOutputPin(GPIOA, LL_GPIO_PIN_0);
	Delay(18000);
	LL_GPIO_SetOutputPin(GPIOA, LL_GPIO_PIN_0);
	Delay(30);
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_0, LL_GPIO_MODE_INPUT);

	while(LL_GPIO_IsInputPinSet(GPIOA, LL_GPIO_PIN_0));

	while(!LL_GPIO_IsInputPinSet(GPIOA, LL_GPIO_PIN_0));

	while(LL_GPIO_IsInputPinSet(GPIOA, LL_GPIO_PIN_0));


	for(uint8_t i=0; i<5; i++)
	{
		for(uint8_t j=0; j<8; j++)
		{
			while(!LL_GPIO_IsInputPinSet(GPIOA, LL_GPIO_PIN_0));
			Delay(40);

			if(!LL_GPIO_IsInputPinSet(GPIOA, LL_GPIO_PIN_0))
			{
				Temp_DHT11[i] &= ~(1<<(7-j));
			}
			else
			{
				Temp_DHT11[i]	|= (1<<(7-j));
				while(LL_GPIO_IsInputPinSet(GPIOA, LL_GPIO_PIN_0));
			}
		}
	}

}

uint16_t LM35()
{
	uint32_t Temp_LM35;

	LL_ADC_REG_StartConversionSWStart(ADC1);
	while(!LL_ADC_IsActiveFlag_EOCS(ADC1));
	Temp_LM35=LL_ADC_REG_ReadConversionData12(ADC1);
	LL_ADC_ClearFlag_EOCS(ADC1);

	Temp_LM35=(Temp_LM35*3300)/4096;

	return Temp_LM35/10;
}

void DS1302(uint8_t DS_WR,uint8_t *data)
{
	LL_GPIO_SetPinMode(Data, LL_GPIO_MODE_OUTPUT);
	LL_GPIO_SetOutputPin(CE);
	Delay(10);

	for(uint8_t i=0; i<8; i++)
	{

		if((DS_WR >> i) & 0x01)
		{
			LL_GPIO_SetOutputPin(Data);
		}
		else
		{
			LL_GPIO_ResetOutputPin(Data);
		}
		Delay(10);
		LL_GPIO_SetOutputPin(Clock);
		Delay(100);
		LL_GPIO_ResetOutputPin(Clock);
		Delay(100);
	}

	if(DS_WR & 0X01)
	{
		LL_GPIO_SetPinMode(Data, LL_GPIO_MODE_INPUT);

		*data=0;
		for(uint8_t i = 0; i < 8; i++) {

			if(LL_GPIO_IsInputPinSet(Data))
			{
				*data |=(1<<i);
			}

			LL_GPIO_SetOutputPin(Clock);
			Delay(100);
			LL_GPIO_ResetOutputPin(Clock);
			Delay(100);
		}

	}
	else
	{
		LL_GPIO_SetPinMode(Data, LL_GPIO_MODE_OUTPUT);
		for(uint8_t i=0; i<8; i++)
		{

			if((*data >> i) & 0x01)
			{
				LL_GPIO_SetOutputPin(Data);
			}
			else
			{
				LL_GPIO_ResetOutputPin(Data);
			}
			LL_GPIO_SetOutputPin(Clock);
			Delay(100);
			LL_GPIO_ResetOutputPin(Clock);
			Delay(100);
		}
	}
	LL_GPIO_ResetOutputPin(CE);
	LL_GPIO_SetPinMode(Data, LL_GPIO_MODE_OUTPUT);
	Delay(100);
}

uint8_t bcdToDec(uint8_t val) {
    return ( (val / 16 * 10) + (val % 16) );
}

int main(void)
{


	//Timer
	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_TIM1);
	LL_TIM_SetPrescaler(TIM1, 1599);
	LL_TIM_SetAutoReload(TIM1, 10000);
	LL_TIM_EnableIT_UPDATE(TIM1);
	LL_TIM_EnableCounter(TIM1);
	/*NVIC_SetPriority(TIM1_UP_TIM10_IRQn,1);
	NVIC_EnableIRQ(TIM1_UP_TIM10_IRQn);*/

	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_TIM2);
	LL_TIM_SetPrescaler(TIM2, 16);

	//GIPO
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_0, LL_GPIO_MODE_OUTPUT);

	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_5, LL_GPIO_MODE_OUTPUT);
	LL_GPIO_SetOutputPin(GPIOA, LL_GPIO_PIN_5);

	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOB);
	LL_GPIO_SetPinMode(Clock, LL_GPIO_MODE_OUTPUT);
	LL_GPIO_ResetOutputPin(Clock);
	LL_GPIO_SetPinMode(Data, LL_GPIO_MODE_OUTPUT);
	LL_GPIO_SetPinMode(CE, LL_GPIO_MODE_OUTPUT);
	LL_GPIO_ResetOutputPin(CE);

	//ADC
	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_ADC1);
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_1, LL_GPIO_MODE_ANALOG);
	LL_GPIO_SetPinPull(GPIOA, LL_GPIO_PIN_1, LL_GPIO_PULL_NO);
	LL_ADC_SetCommonClock(__LL_ADC_COMMON_INSTANCE(ADC1), LL_ADC_PATH_INTERNAL_NONE);
	LL_ADC_SetResolution(ADC1, LL_ADC_RESOLUTION_12B);
	LL_ADC_SetDataAlignment(ADC1, LL_ADC_DATA_ALIGN_RIGHT);
	LL_ADC_SetSequencersScanMode(ADC1, LL_ADC_SEQ_SCAN_DISABLE);
	LL_ADC_REG_SetSequencerRanks(ADC1, LL_ADC_REG_RANK_1, LL_ADC_CHANNEL_1);
	LL_ADC_SetChannelSamplingTime(ADC1, LL_ADC_CHANNEL_1, LL_ADC_SAMPLINGTIME_480CYCLES);
	LL_ADC_Enable(ADC1);


	//UART
	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_USART1);
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_9, LL_GPIO_MODE_ALTERNATE);
	LL_GPIO_SetAFPin_8_15(GPIOA, LL_GPIO_PIN_9, LL_GPIO_AF_7);
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_10, LL_GPIO_MODE_ALTERNATE);
	LL_GPIO_SetAFPin_8_15(GPIOA, LL_GPIO_PIN_10, LL_GPIO_AF_7);
	LL_USART_SetTransferDirection(USART1, LL_USART_DIRECTION_TX_RX);
	LL_USART_ConfigCharacter(USART1, LL_USART_DATAWIDTH_8B, LL_USART_PARITY_NONE, LL_USART_STOPBITS_1);
	LL_USART_SetBaudRate(USART1, 16000000, 16, 9600);
	LL_USART_ConfigAsyncMode(USART1);
	LL_USART_Enable(USART1);

	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_USART2);
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_2, LL_GPIO_MODE_ALTERNATE);
	LL_GPIO_SetAFPin_0_7(GPIOA, LL_GPIO_PIN_2, LL_GPIO_AF_7);
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_3, LL_GPIO_MODE_ALTERNATE);
	LL_GPIO_SetAFPin_0_7(GPIOA, LL_GPIO_PIN_3, LL_GPIO_AF_7);
	LL_USART_SetTransferDirection(USART2, LL_USART_DIRECTION_TX_RX);
	LL_USART_ConfigCharacter(USART2, LL_USART_DATAWIDTH_8B, LL_USART_PARITY_NONE, LL_USART_STOPBITS_1);
	LL_USART_SetBaudRate(USART2, 16000000, 16, 115200);
	LL_USART_ConfigAsyncMode(USART2);
	LL_USART_Enable(USART2);


	uint8_t raw_seconds = 0, raw_minutes = 0, raw_hours = 0;
	uint8_t seconds = 0, minutes = 0, hours = 0;
	char time_msg[40];
	uint8_t time_len;
	uint8_t wr_disable = 0x00;
	uint8_t sekundy = 0x00;
	uint8_t minuty  = 0x25;
	uint8_t godziny = 0x14;

	DS1302(0x8E, &wr_disable);
	DS1302(0x80, &sekundy);
	DS1302(0x82, &minuty);
	DS1302(0x84, &godziny);


while(1)
{

	if (LL_USART_IsActiveFlag_RXNE(USART2))
	    {
	        uint8_t received_data = LL_USART_ReceiveData8(USART2);
	        while (!LL_USART_IsActiveFlag_TXE(USART2));
	        LL_USART_TransmitData8(USART2, received_data);

	    }

	if (LL_USART_IsActiveFlag_RXNE(USART1)) {
		char msg[60];
		uint8_t len;
	        uint8_t Receive = LL_USART_ReceiveData8(USART1);
	        while (!LL_USART_IsActiveFlag_TXE(USART1));
	        if(Receive == '1') {
	            DHT11();
	           uint32_t Temp=LM35();
	           len=sprintf(msg, "LM35: Temp: %lu C, \r\n", Temp);
	           for(uint8_t i=0; i<len; i++)
	           {
        		   while (!LL_USART_IsActiveFlag_TXE(USART1));
        		   LL_USART_TransmitData8(USART1, msg[i]);
	           }

	           	   len=sprintf(msg, "DHT11: Temp: %d.%d C, Wilg: %d.%d %%\r\n", Temp_DHT11[2],Temp_DHT11[3],Temp_DHT11[0],Temp_DHT11[1]);
	        	   for(uint8_t i=0; i<len; i++)
	        	   {
	        		   while (!LL_USART_IsActiveFlag_TXE(USART1));
	        		   LL_USART_TransmitData8(USART1, msg[i]);
	        	   }


	        }
	        if (Receive == '2') {

	            DS1302(0x81, &raw_seconds);
	            DS1302(0x83, &raw_minutes);
	            DS1302(0x85, &raw_hours);

	            seconds = bcdToDec(raw_seconds & 0x7F);
	            minutes = bcdToDec(raw_minutes);
	            hours	= bcdToDec(raw_hours & 0x3F);


	            time_len = sprintf(time_msg, "Czas: %02d:%02d:%02d\r\n", hours, minutes, seconds);

	            for(uint8_t i = 0; i < time_len; i++) {
	                while (!LL_USART_IsActiveFlag_TXE(USART1));
	                LL_USART_TransmitData8(USART1, time_msg[i]);
	            }
	        }
	    }


}



}
